name: 😎 Buildar automáticamente

on:
  push:
    tags:
      - 'v*' # v1.0.0, v1.0.1, ...

jobs:
  build:
    name: 🎮 Buildar o projeto
    runs-on: windows-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: RPG/Library
          key: Library-${{ hashFiles('RPG/Assets/**', 'RPG/Packages/**', 'RPG/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: "RPG"
          targetPlatform: StandaloneWindows64
          buildName: "SangueFrio"
          versioning: Tag

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: SangueFrio
          path: build

      # Release
      - name: Create Release
        run: ls -l
        uses: softprops/action-gh-release@v2
        with:
          files: SangueFrio.zip
