name: 😎 Buildar automáticamente

# Cria uma build para cada tag criada no formato v*.*.*
# Recomendo olhar a doc para ver todos os possiveis eventos: https://docs.github.com/pt/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  push:
    tags:
      - 'v*' # v1.0.0, v1.0.1, ...

jobs:
  build:
    name: 🎮 Buildar o projeto
    runs-on: windows-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      # No github, meu projeto Unity está localizado na pasta RPG, por isso o caminho RPG/Library, RPG/Assets, RPG/Packages, RPG/ProjectSettings.
      - uses: actions/cache@v4
        with:
          path: RPG/Library
          key: Library-${{ hashFiles('RPG/Assets/**', 'RPG/Packages/**', 'RPG/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      # Aqui eu recomendo olhar a documentação do unity-builder para entender os parâmetros e como defini-los
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: "RPG"
          targetPlatform: StandaloneWindows64
          buildName: "SangueFrio"
          versioning: Tag

      # Dá upload da build para artifact (não é necessário, mas é bom caso dê merda nos outros passos)
      # O unity-builder gera uma pasta para cada plataforma, só estamos usando a StandaloneWindows64
      - uses: actions/upload-artifact@v4
        with:
          name: SangueFrio
          path: ./build/SangueFrio/StandaloneWindows64/
      
      - uses: actions/download-artifact@v4
        with:
<<<<<<< Updated upstream
=======
<<<<<<< Updated upstream
<<<<<<< HEAD
          path: ./release/build.zip
=======
          path: ./release/
      
      - uses: vimtor/action-zip@v1.2
        with:
          files: ./release/*
          dest: release.zip
      
      - name: Display structure of downloaded files
        run: ls -R
>>>>>>> Stashed changes

=======
>>>>>>> Stashed changes
          path: ./release/
      
      - uses: vimtor/action-zip@v1.2
        with:
          files: ./release/
          dest: release.zip
      
      # Passo de debug, mostra como está a estrutura internamente do sistema (não do zip)
      - name: Display structure of downloaded files
        run: ls -R

      # Gera a release no github
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
<<<<<<< Updated upstream
          files: release.zip
=======
<<<<<<< Updated upstream
<<<<<<< HEAD
          files: ./release/build.zip
=======
          files: release.zip
>>>>>>> origin/main
=======
          files: release.zip
>>>>>>> Stashed changes
>>>>>>> Stashed changes
